### PR TITLE
Tasseled Cap Transformations

### LINKED ISSUE #5: Tasseled Cap Transformations
See the original feature request on [eemont](https://github.com/davemlz/eemont/issues/46).

This would add an `ee_extra.Transformations` module with a `tasseledCap` function to calculate [tasseled cap](https://en.wikipedia.org/wiki/Tasseled_cap_transformation) brightness, wetness, and greenness bands from an input `ee.Image` from the MODIS, Landsat 5/7/8, or Sentinel-2 platforms. 

A couple design questions:

- Should the tasseled cap bands be added to the original image (like `spectralIndices`) or returned as a new `ee.Image`?
- How strict should the platform matching be? For example, published [Landsat 8 coefficients](https://www.tandfonline.com/doi/abs/10.1080/2150704X.2014.915434?journalCode=trsl20) were generated for at-sensor reflectance and *technically* aren't accurate for TOA or Surface Reflectance (see the warning on [Hexagon Geospatial](https://geospatialcommunity.hexagon.com/s/article/Tasseled-Cap-Transformation-for-Landsat-8)). Should that be strictly enforced or just mentioned in the docs?

Feel free to assign me, thanks!

### PR DESCRIPTION
**Pull request by aazuspan**
- Fix #5 by adding `tasseledCap` function to `Spectral` module for calculating brightness, greenness, and wetness from Sentinel-2, MODIS, and Landsat 4-8 images and image collections 
- Add utility function for matching platforms to tasseled cap coefficients
- Update tests and docs to include `tasseledCap`

Let me know if any changes are needed :)

### CODE REVIEW

**Comment by davemlz** [comment]
Wow! This was pretty fast, @aazuspan! :rocket: Awesome job!

Since the last time we had troubles with the online testing (in eemont), I will download and test the features in local and then I will merge the PR!

Thank you very much, @aazuspan!

**Comment by davemlz** [comment]
Works perfectly! Amazing job, @aazuspan! I'm merging it now :rocket:

If you want to add it to `eemont`, you can do it now :) `ee_extra` is already a dep, so you can just call `ee_extra.Spectral.core.tasseledCap` in the `image.py` and `imagecollection.py` modules to extend the `ee` classes!

Soon we will be releasing the next version of `ee_extra`! :)

**Comment by aazuspan** [comment]
Thanks @davemlz! I'll start adding this to `eemont` now.

**Comment by davemlz** [comment]
Great, @aazuspan! Let me know if you need anything! :)

**Pull request merged**
